apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.services.notification.replicas }}
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: {{ .Values.imageRegistry }}/{{ .Values.services.notification.image }}:{{ .Values.services.notification.tag }}
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: novapay-config
            - secretRef:
                name: novapay-secret
          env:
            - name: PORT
              value: {{ .Values.services.notification.port | quote }}
            - name: DATABASE_URL
              value: "postgresql://{{ .Values.postgres.auth.username }}:{{ .Values.postgres.auth.password }}@{{ .Values.postgres.auth.host | default (printf "%s-postgres" .Release.Name) }}:5432/{{ .Values.postgres.auth.database }}?schema=notification"
            - name: REDIS_URL
              value: "redis://:{{ .Values.redis.auth.password }}@{{ .Values.redis.host | default (printf "%s-redis-master" .Release.Name) }}:6379"

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: {{ .Values.services.notification.port }}
