apiVersion: v1
kind: Secret
metadata:
  name: novapay-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.auth.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.auth.password | quote }}
  POSTGRES_DB: {{ .Values.postgres.auth.database | quote }}
  REDIS_PASSWORD: {{ .Values.redis.auth.password | quote }}
  JWT_SECRET: {{ .Values.jwt.secret | quote }}
  INTERNAL_SECRET: {{ .Values.internalSecret | quote }}
