services:
  postgres:
    image: postgres:16-alpine
    container_name: novapay-postgres
    environment:
      POSTGRES_USER: novapay
      POSTGRES_PASSWORD: novapay_secret
      POSTGRES_DB: novapay
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-schemas.sql:/docker-entrypoint-initdb.d/01-schemas.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U novapay"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: novapay-redis
    command: redis-server --requirepass redis_secret --appendonly yes
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis_secret", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  kong:
    image: kong:3.6-ubuntu
    container_name: novapay-kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    ports:
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:8001:8001"
    volumes:
      - ./kong/kong.yml:/etc/kong/kong.yml:ro
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: novapay-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@novapay.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "127.0.0.1:5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data:
