apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.services.auth.replicas }}
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: {{ .Values.imageRegistry }}/{{ .Values.services.auth.image }}:{{ .Values.services.auth.tag }}
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: novapay-config
            - secretRef:
                name: novapay-secret
          env:
            - name: PORT
              value: {{ .Values.services.auth.port | quote }}
            - name: DATABASE_URL
              value: "postgresql://{{ .Values.postgres.auth.username }}:{{ .Values.postgres.auth.password }}@{{ .Release.Name }}-postgres:5432/{{ .Values.postgres.auth.database }}?schema=auth"
            - name: REDIS_URL
              value: "redis://:{{ .Values.redis.auth.password }}@{{ .Release.Name }}-redis-master:6379"
          ports:
            - containerPort: {{ .Values.services.auth.port }}
