apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: auth-service
  ports:
    - port: {{ .Values.services.auth.port }}
      targetPort: {{ .Values.services.auth.port }}
