apiVersion: v1
kind: Secret
metadata:
  name: novapay-secret
  namespace: novapay
type: Opaque
stringData:
  POSTGRES_USER: novapay
  POSTGRES_PASSWORD: novapay_secret
  POSTGRES_DB: novapay
  REDIS_PASSWORD: redis_secret
  JWT_SECRET: novapay_super_secret_jwt_key_min_32_chars
  INTERNAL_SECRET: novapay_internal_secret_key
