apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: novapay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: giathan/novapay-auth-service:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: novapay-config
            - secretRef:
                name: novapay-secret
          env:
            - name: PORT
              value: "3001"
            - name: DATABASE_URL
              value: "postgresql://novapay:novapay_secret@postgres:5432/novapay?schema=auth"
            - name: REDIS_URL
              value: "redis://:redis_secret@redis:6379"
          ports:
            - containerPort: 3001
